export const SET_MASTER_DATA = 'SET_MASTER_DATA';
export const SET_FIRST_API_DATA = 'SET_FIRST_API_DATA';
export const SET_SECOND_API_DATA = 'SET_SECOND_API_DATA';
export const SET_THIRD_API_DATA = 'SET_THIRD_API_DATA';
